//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./gifs_types');
//HELPER FUNCTIONS AND STRUCTURES

ObtenerGifs_ping_args = function(args) {
};
ObtenerGifs_ping_args.prototype = {};
ObtenerGifs_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_ping_args.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifs_ping_result = function(args) {
};
ObtenerGifs_ping_result.prototype = {};
ObtenerGifs_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_ping_result.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifs_obtenerTopGifs_args = function(args) {
};
ObtenerGifs_obtenerTopGifs_args.prototype = {};
ObtenerGifs_obtenerTopGifs_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_obtenerTopGifs_args.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_obtenerTopGifs_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifs_obtenerTopGifs_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ObtenerGifs_obtenerTopGifs_result.prototype = {};
ObtenerGifs_obtenerTopGifs_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Gifs();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_obtenerTopGifs_result.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_obtenerTopGifs_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifs_zip_args = function(args) {
};
ObtenerGifs_zip_args.prototype = {};
ObtenerGifs_zip_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_zip_args.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_zip_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifs_zip_result = function(args) {
};
ObtenerGifs_zip_result.prototype = {};
ObtenerGifs_zip_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ObtenerGifs_zip_result.prototype.write = function(output) {
  output.writeStructBegin('ObtenerGifs_zip_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ObtenerGifsClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
ObtenerGifsClient.prototype = {};
ObtenerGifsClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

ObtenerGifsClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new ObtenerGifs_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ObtenerGifsClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ObtenerGifs_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ObtenerGifsClient.prototype.obtenerTopGifs = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_obtenerTopGifs();
};

ObtenerGifsClient.prototype.send_obtenerTopGifs = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('obtenerTopGifs', Thrift.MessageType.CALL, this.seqid);
  var args = new ObtenerGifs_obtenerTopGifs_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ObtenerGifsClient.prototype.recv_obtenerTopGifs = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ObtenerGifs_obtenerTopGifs_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('obtenerTopGifs failed: unknown result');
};
ObtenerGifsClient.prototype.zip = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_zip();
};

ObtenerGifsClient.prototype.send_zip = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('zip', Thrift.MessageType.CALL, this.seqid);
  var args = new ObtenerGifs_zip_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
ObtenerGifsProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ObtenerGifsProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ObtenerGifsProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new ObtenerGifs_ping_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ping(function (err, result) {
    var result = new ObtenerGifs_ping_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ObtenerGifsProcessor.prototype.process_obtenerTopGifs = function(seqid, input, output) {
  var args = new ObtenerGifs_obtenerTopGifs_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.obtenerTopGifs(function (err, result) {
    var result = new ObtenerGifs_obtenerTopGifs_result((err != null ? err : {success: result}));
    output.writeMessageBegin("obtenerTopGifs", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ObtenerGifsProcessor.prototype.process_zip = function(seqid, input, output) {
  var args = new ObtenerGifs_zip_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.zip()
}

